//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace МСЧ52
{
    using System;
    using System.Collections.Generic;
    
    public partial class Mesto_rab_uch
    {
        public int Id { get; set; }
        public int IdPastients { get; set; }
        public string City { get; set; }
        public string NazvOrg { get; set; }
        public string Podrazdeleniya { get; set; }
    
        public virtual Pastients Pastients { get; set; }
    }
}
