//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace МСЧ52
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class Inform_sistema3Entities : DbContext
    {
        public Inform_sistema3Entities()
            : base("name=Inform_sistema3Entities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Diagnosis> Diagnosis { get; set; }
        public virtual DbSet<Doctors> Doctors { get; set; }
        public virtual DbSet<Facilities> Facilities { get; set; }
        public virtual DbSet<Mesto_rab_uch> Mesto_rab_uch { get; set; }
        public virtual DbSet<Pastients> Pastients { get; set; }
        public virtual DbSet<Uchastok> Uchastok { get; set; }
        public virtual DbSet<Users> Users { get; set; }
    }
}
